
default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV['RAILS_MAX_THREADS'] { 5 } %>

development:
  <<: *default
  database: gefc_api_development
test:
  <<: *default
  database: gefc_api_test
staging:
  <<: *default
  database: <%= ENV['RDS_DATABASE'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOST'] %>
  post: 5432

production:
  <<: *default
  database: <%= ENV['RDS_DATABASE'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOST'] %>
  post: 5432
