default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 20 } %>
  database: <%= ENV.fetch('POSTGRES_DATABASE') { "gefc_api" } %>
  username: <%= ENV.fetch('POSTGRES_USERNAME') { "postgres" }%>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') {} %>
  host: <%= ENV.fetch('POSTGRES_HOST') { "localhost" } %>
  post: <%= ENV.fetch('POSTGRES_PORT') { 5432 } %>

development:
  <<: *default
  database: gefc_api_development

test:
  <<: *default
  database: gefc_api_test

staging:
  <<: *default

production:
  <<: *default
