---
:verbose: true
:concurrency: <%= ENV['RAILS_MAX_THREADS'] || 3 %>
:max_retries: 30

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 60

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/

:queues:
  - default
