name: Deploy with Capistrano

on:
  push:
    branches:
    - develop

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true
    - uses: miloserdow/capistrano-deploy@master
      with:
        target: staging
        deploy_key: ${{ secrets.ID_RSA_ENC_PASS }}
        enc_rsa_key_pth: ./config/deploy/encrypted_keys/deploy_gefc_staging_rsa_enc